all:
	./test.sh slr
	./test.sh slr eunitr
	./test.sh lr1
	./test.sh lalr
	./test.sh lr0
	./test.sh ll1

testv:
	./valgrind.sh slr
	./valgrind.sh slr eunitr
	./valgrind.sh lr1
	./valgrind.sh lalr
	./valgrind.sh lr0
	./valgrind.sh ll1
